name: Stock Price Notification

on:
  schedule:
    - cron: '0 22 * * *'  # UTCの22時、JSTの7時

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance requests

    - name: Run script
      run: python send_stock_update.py
